### ISSUE TITLE
How I can add more fonts?

### ISSUE THREAD

**Issue by xlmnxp** [openscad/openscad-playground#21]
Hello, I have the following code

```scad
/*
  Hello there!

  If you're new to OpenSCAD, please learn the basics here:
  https://openscad.org/documentation.html

  There are lots of amazing libraries in the OpenSCAD ecosystem
  (see this list: https://openscad.org/libraries.html).

  Some of these libraries are bundled with this playground
  (search for "demo" or "example" in the file explorer above)
  and can be included directly from your models.

  Any bugs (this is an Alpha!) or ideas of features?
  https://github.com/openscad/openscad-playground/issues/new
*/

// Click on Render or hit F6 to do a fine-grained rendering.
$fn=$preview ? 20 : 100;

translate([-24,0,0]) {
  union() {
    cube(15, center=true);
    sphere(10);
  }
}

intersection() {
  cube(15, center=true);
  sphere(10);
}

translate([24,0,0]) {
  difference() {
    cube(15, center=true);
    sphere(10);
  }
}

translate([0, -30, -12])
  linear_extrude(1)
    text("السلام", halign="center", valign="center", font="Noto Sans Arabic");
```

it contain Arabic word but it don't render in playground correctly
![image](https://github.com/openscad/openscad-playground/assets/20779154/f8e57c4c-dd38-4cd1-9904-a62722a6660f)

but it render fine inside OpenSCAD
![image](https://github.com/openscad/openscad-playground/assets/20779154/6fe03127-0e0a-4811-b09a-180634ad923d)

**Comment by ochafik** [comment]
@xlmnxp if you know of any good font(s) w/ Arabic script (& more) in a compatible OSS license, we should be able to ship them in the playground. For now the [Makefile only bundles these](https://github.com/openscad/openscad-playground/blob/f52f8d5333c904ade0ee1e212212a4f547a68a49/Makefile#L63).

Might also need an update to https://github.com/openscad/openscad-playground/blob/f52f8d5333c904ade0ee1e212212a4f547a68a49/src/fs/zip-archives.ts#L24

**Comment by xlmnxp** [comment]
@ochafik noto sans arabic

**Comment by ochafik** [comment]
Sorry this took so long.

I've added the Noto fonts for all the scripts I could find (including Arabic), except CJK (too heavy for now): you can test them [with this example](https://ochafik.com/openscad2/#H4sIAAAAAAAAE6VZYW8cxRn+K6+2kTiLte+c4CLOudDYoQGSACJWqypnRXO7c7tD5mZOM7NnX4Ilg6GgIqsQCFJbCG5jjEmMCYYkroXzK1oC32aj9ot/RTWzu3e39i3Xqvdhb3fe533mnZl3nnfu9prTRgK1pFO95iBPkQ5+BanQqTrlNkXdQPCI+RPSQ77jOk2MVCSwdKqXnBZipMmpbUZSjXsycFyHoqvd8YgRzhzXQVKSVttxHYGZj8W4xykX0pl3Hckj4Vmea067sDuPM4WZcqoOYR6NfAwnZ16+eP54WaoEc6rOjlhE5CmZWetMeoK0Va3unBaoQby6Mw3lMlxKntzTooUZQcydQZQwLLE7g1mAKHHP4A5iKECCuM+xgBIZus+pkPA28dyzmIvAeJ2NXkMCKeKejUQruhIS93ncEHjBfRF1kKU7hxhDPnLPhS0s3POIuxc4Czg13he6iLWQcF8WpIvci4SFiCJ3DrUIdedCRNw50sAKMXeONAlDQThvB6S6FNfqzqs4iCgS2YDSR3eGU999QSFKPAtvcqZk7VKdAQDUnZe44vASkldCyCbETWzl8jBzNenOsPaQKewiYnKIt2ke5jUUkQQ6jDlbmQL/zDwivmxZh9qSlS7oILWO4IfZF8/B3OwwUz+BCnroA0Z0kuVdAU9mHsGSJW0BS2YexZJmfBFLah7JkmyXQpbEPIIl2WsFHIlxBEO2TYfZ0p1bQJ9aR/DbXV/EYGwj/M8jXuB9HvERvj2dGWpMpKeAPLWO6MDKVgGDtY3wTwWvgCG1juCwYlnAYG2j/ENUlITGNMo70ecigsQ6kiPRdmubn7aSHTFPEc6gTbwrl42AlyhiQYQC7AKpVcagltAQOAkVeP11IHAKKGYlK/ZjidF8ns1rNTwJUokSGUBUgcjLEfNxsySVuNwkzE9YLpF5F7JuxwY8Et7hoZEnJw8hq5CxTWfVCGoD3kl5HrPGQGCsCAugBkkZv9xBtJSWrkv9Cu5C3fnx25/e+vGLn96uO/PuAKBXM6Du/GPnn3/9YfmHd3KQgYIAdSfeuh5vvRFvfRhvfZWH9WoD1B29sak3tvXGrv5iVW/c0BsP9cbdPtxU37qTFYIq1J1/7a/9+/P9HGGuGhjO9U29vq3Xd/Xnq3p9XX+eDzM9ciTY5zGlPG/uVwQzinfvxu++F7/7aQ4zoPcGs3I9Xnk/XvmLva7FK1/HK5/GKx/EK+/nvfr6bqK8valvb+vbu/rOqr69ru+8cwjck3ED3tzVm+tgvr5c1Zt39ZfLoDff1ps39OZDvbmTc+1pN9SdR18++uTRjUf58AekGerOwcY3Bxu7BxvXDza+P9h442DjzsHGtm1ZyXn1RdsEtLOpd7b1zq7+dlXv3NA7D/XO3Tw81WczQTc/i2/um+tn1+Obf4xv7uaQiRIb0r3beu+u3vuz3tvRe6t67yO9dy8HHRReQ7x2N15bi9fux2t/i9c2IV67Pfgcr61BvHYrXruVJ+kJtKFY/lO8/Fa8vBcv/z1efjNe/iRe3oqXb8TLd3JOmSKbMLc29da23trVX63qrRt666Heyo+9L78Gfv/3+v6efvCRvn9fP/hUP1jW97/RD/6Q88jE1uC37+ntW3r7hv561Vy3t/XXq3lwoqwGu3tb736hd7+xNx/p3fx09UXUYPc/1vvL+uGO/v49vb+u93f0/oa9/1jvf6D39+z9LXOz/6Y1Heq1r6ZQdx5/d/fxvVuP7334+F4Km3chUZyBfZWID/ZCnqpRrQextJks1bKbtDujXzVzSZ8TnbfXhNL+3CnVnUCgbt1JhVEJxCRFCpcuVVzwcSMK4FkY/2UFqjB+vOJCZT5FGqFC4jJeVCLycWlQWRVeVKW80B4KLvvYII3o20Ch7lSz3w9uEvDYIYf8FORtIaIkYLW642GmBg422adz2J7MQ7kMv+MReIiBqS+gQgxckIAwRKHJhW1ockr5glF/vIhabYqBsMRAKAa82KZcYAGowTvYtZymagngbczMjz0oZ44SyjCDJPGgDLMXz463uB9RnPwkTMM53AzjqUckUYCBNyG1ukCaLtiFdOFYU5aPNVHGESIWYFAhkaA4NBGV2NwI3OIdbEMPMW1jAQHmLaxEt86S5a6BEhHOpuYs5Q1EQWDJaWTKfp0da8rasbbAHYIX4FmYhCpUJianbak5w9kTCgLMsEAKg2whSrGAJvKwkqBCxAwWWi1Dg3I0U1CFqem0ZB3ioUgEZnpZYCbQ0kyBj01WSROo4Mrm7PgzJkVtlsI1s/rlMlxAhA0MEsAnzSYWmHm4lKLsacXkhMT2aDPYbj4N7ndLJlv6TT04FwOWpewm5BTL1LBkIrShPG9nXJon0oSSne+xdB0S9FK2fFzgLGjiQVuQFjF/fsgJa54LscQ2ZRvYJANpEuyb5fUENvPVQYIgMxJpsiXJU5POvPEa9pTpI8mgdGTZaDNJmKERrjtjINshFrg0WemFlrrlRn/Y+1XsG2cvauDS5JQLyXarmaw6zGOm6WUb01Ga86Rlg/C6lJi9VAprRoBErYCyXIbfIEF4JLPtYXdvh8gIUXLV7F0bdgv7xMyRx1ttzjBTctjAsN+PqDg1jiTGsLRYOjrm06UxyHK24j5TcU3CDk7GdA4+MwA34BHw2dIRa84u+4Ow/4Xlx5TGN51vmTnSMls4wCyfM9ZyGV5gDIt0XUAS5mEg6gkJnNEuMIx97ANhkvg998Q19TDFpjQ2kJ/Iu5LLDVGbdCGsTVaO5EZa/TxEcakyMZUb6kC1Gz9h5nX8qZ5yDNnqJiem87ZBhskpw3Bian5smGDksAPQ4UJylP3pCesz+fSE8eonz4kkG5IZKvYvch8v8l8aOk3FszSoeAXzU+kN+miOHZ6gPHbm57An8tjZn8MWTMLx/24Sx/+vJZgs6Pypqf9lBWys7vjx44doilgGXAs8hwaQ7Wl78OxgIQlntfS7NGZQ5TL8VhClMINGFy4gQSIJ50w6UzjZso+/umIfJxhWp4xDUru4LUh40fx5Dm0uJWlQnJ6XKFpwrRlFKuSiJMcgRB0MPvaJhxT2AVFqaTze7goShAoQ80FgmliZDwyTIGxwYRTfIuwJyJ6EJG+qBSRw0oAtUTtqUOKBz1vmoLDABfUXiI8nYC7nQST4RCpBGpHpaIGokEem865lWUBCIKa6E71xmkOlDHlE/WQIAnuYdEyMNvasMM/OVuCVJIQzNgTrfCYZr/mbBVHOAttffgzJSeCFJjCuXJAYw8lQqXa1XLaHANLBHm+1OJMTXATlZJTJIMtXseDlyYlK+dREnTlL89krkF9z0ULmhUZAG47r4MU2F+pIoz3wi9nkbUn10vyS65gznHlDQ3kgnao9bPaRrxDvCha9Zoq6PFIG3eI+dqpOK6KKmPc03IsGvH2iuHCqRseTDnDvyYuk4i1ytce6ZN7GUIraEvuzPeMcatgArdFwOb9oPuM/fdxzXEeGfOH0onnHk1Ca54sh8vlCr8nsh5eiVgOLLKqlpf8A30HOg48aAAA=)

<details>

<summary>show source</summary>

```openscad
include <BOSL2/std.scad>
include <BOSL2/structs.scad>

script="Arabic"; // [Arabic,Armenian,Balinese,Bengali,Devanagari,English,Ethiopic,Georgian,Gujarati,Gurmukhi,Hebrew,Javanese,Kannada,Khmer,Lao,Mongolian,Myanmar,Oriya,Sinhala,Tamil,Thai,Tibetan,Tifinagh]

style="Regular"; // [Regular,Bold,Italic]

fonts=[
    "Noto Naskh Arabic",
    // "Noto Naskh Arabic:style=Bold",
    "Noto Sans",
    // "Noto Sans:style=Bold",
    // "Noto Sans:style=Italic",
    "Noto SansArmenian",
    // "Noto SansArmenian:style=Bold",
    "Noto SansBalinese",
    "Noto SansBengali",
    // "Noto SansBengali:style=Bold",
    "Noto Sans CJK TC",
    "Noto SansDevanagari",
    // "Noto SansDevanagari:style=Bold",
    "Noto SansEthiopic",
    // "Noto SansEthiopic:style=Bold",
    "Noto SansGeorgian",
    // "Noto SansGeorgian:style=Bold",
    "Noto SansGujarati",
    // "Noto SansGujarati:style=Bold",
    "Noto SansGurmukhi",
    // "Noto SansGurmukhi:style=Bold",
    "Noto SansHebrew",
    // "Noto SansHebrew:style=Bold",
    "Noto SansJavanese",
    "Noto SansKannada",
    // "Noto SansKannada:style=Bold",
    "Noto SansKhmer",
    // "Noto SansKhmer:style=Bold",
    "Noto SansLao",
    // "Noto SansLao:style=Bold",
    "Noto SansMongolian",
    "Noto SansMyanmar",
    // "Noto SansMyanmar:style=Bold",
    "Noto SansOriya",
    // "Noto SansOriya:style=Bold",
    "Noto SansSinhala",
    // "Noto SansSinhala:style=Bold",
    "Noto SansTamil",
    // "Noto SansTamil:style=Bold",
    "Noto SansThai",
    // "Noto SansThai:style=Bold",
    "Noto SansTibetan",
    // "Noto SansTibetan:style=Bold",
    "Noto SansTifinagh",
];

function pick_font(language, i=0) =
    i < 0 || i > len(fonts)
        ? "Noto Sans" + str(i)
        : is_undef(str_find(fonts[i], language))
            ? pick_font(language, i=i+1)
            : fonts[i];

font = pick_font(script);

greeting = struct_val([
    ["Arabic", "سلام"],
    ["Armenian", "Բարև"],
    ["Balinese", "ᬒᬁᬓᬭ"],
    ["Bengali", "নমস্কার"],
    // ["CJK TC": "你好"],
    ["Devanagari", "नमस्ते"],
    ["English", "Hello"],
    ["Ethiopic", "ሰላም"],
    ["Georgian", "გამარჯობა"],
    ["Gujarati", "નમસ્તે"],
    ["Gurmukhi", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ"],
    ["Hebrew", "שלום"],
    ["Javanese", "ꦱꦸꦒꦼꦁꦫꦮꦸꦃ"],
    ["Kannada", "ನಮಸ್ಕಾರ"],
    ["Khmer", "សួស្តី"],
    ["Lao", "ສະບາຍດີ"],
    ["Mongolian", "ᠰᠠᠶᠢᠨ ᠪᠠᠶᠢᠨᠠ ᠣᠣ"],
    ["Myanmar", "မင်္ဂလာပါ"],
    ["Oriya", "ନମସ୍କାର"],
    ["Sinhala", "ආයුබෝවන්"],
    ["Tamil", "வணக்கம்"],
    ["Thai", "สวัสดี"],
    ["Tibetan", "བཀྲ་ཤིས་བདེ་ལེགས།"],
    ["Tifinagh", "ⴰⵣⵓⵍ"],
], script, "Hello");

echo(script=script, 
    greeting=greeting,
    font=font,
    style=style);

color("gray")
    translate([0, debug ? -60 : -20, 0])
    linear_extrude(1)
        text(
            greeting,
            font=str(font, ":style=", style),
            script=script,
            halign="center",
            valign="center");

// You can find the original for the following example in the file explorer above,
// under openscad / examples / Basic / CSG-modules.scad

// CSG-modules.scad - Basic usage of modules, if, color, $fs/$fa

// Change this to false to remove the helper geometry
debug = true;

// Global resolution
$fs=$preview ? 1 : 0.1;  // Don't generate smaller facets than 0.1 mm
$fa=$preview ? 15 : 5;    // Don't generate larger angles than 5 degrees

rotate([-90, 0, 0]) {
  // Main geometry
  difference() {
      intersection() {
          body();
          intersector();
      }
      holes();
  }

  // Helpers
  if (debug) helpers();
}

// Core geometric primitives.
// These can be modified to create variations of the final object

module body() {
    color("Blue") sphere(10);
}

module intersector() {
    color("Red") cube(15, center=true);
}

module holeObject() {
    color("Lime") cylinder(h=20, r=5, center=true);
}

// Various modules for visualizing intermediate components

module intersected() {
    intersection() {
        body();
        intersector();
    }
}

module holeA() rotate([0,90,0]) holeObject();
module holeB() rotate([90,0,0]) holeObject();
module holeC() holeObject();

module holes() {
    union() {
        holeA();
        holeB();
        holeC();
    }
}

module helpers() {
    // Inner module since it's only needed inside helpers
    module line() color("Black") cylinder(r=1, h=10, center=true);

    scale(0.5) {
        translate([-30,0,-40]) {
            intersected();
            translate([-15,0,-35]) body();
            translate([15,0,-35]) intersector();
            translate([-7.5,0,-17.5]) rotate([0,30,0]) line();
            translate([7.5,0,-17.5]) rotate([0,-30,0]) line();
        }
        translate([30,0,-40]) {
            holes();
            translate([-10,0,-35]) holeA();
            translate([10,0,-35]) holeB();
            translate([30,0,-35]) holeC();
            translate([5,0,-17.5]) rotate([0,-20,0]) line();
            translate([-5,0,-17.5]) rotate([0,30,0]) line();
            translate([15,0,-17.5]) rotate([0,-45,0]) line();
        }
        translate([-20,0,-22.5]) rotate([0,45,0]) line();
        translate([20,0,-22.5]) rotate([0,-45,0]) line();
    }
}

echo(version=version());
// Written by Marius Kintel <marius@kintel.net>
//
// To the extent possible under law, the author(s) have dedicated all
// copyright and related and neighboring rights to this software to the
// public domain worldwide. This software is distributed without any
// warranty.
//
// You should have received a copy of the CC0 Public Domain
// Dedication along with this software.
// If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

```

</details>

I'm hoping to add support for custom files (including fonts) in a near future.

**Comment by xlmnxp** [comment]
@ochafik thank you too much
