### ISSUE TITLE
Keep camera position between renders

### ISSUE THREAD

**Issue by remcoder** [openscad/openscad-playground#22]
When editing, a new stl is rendered and viewed but the camera position resets. But I often zoom in on details and I would like to keep the camera there.

[It seems possible to pass initial camera props to the stl viewer.](https://github.com/gabotechs/react-stl-viewer/issues/41)

**Comment by ochafik** [comment]
Filed https://github.com/gabotechs/react-stl-viewer/issues/54 as I don't think there's currently a way to know where the camera is
