### ISSUE TITLE
Relative paths in libraries don't work.

### ISSUE THREAD

**Issue by nophead** [openscad/openscad-playground#32]
I see NopSCADlib is included in the libraries but it doesn't work because it uses relative paths and these aren't resolved properly. Oddly the example projects in NopSCADlib work but none of the library tests work. So it seems relative paths work when the library is use by a project but not by when used by tests inside the library itself.

**Comment by ochafik** [comment]
Hi @nophead 

Thanks for reporting! Quick thoughts:
- Relative links are broken b/c I'm currently aliasing the input file to a fixed location in the virtual FS used by Emscripten. Shouldn't be too hard to fix this (famous last words)
- NopSCADlib/tests subfolder is currently [skipped](https://github.com/openscad/openscad-playground/blob/aa7513a107cd013eb6ece5a906bfc2d981fcf1ea/Makefile#L100), should I add it back?

(btw, big fan of your libs here!)

**Comment by nophead** [comment]
I test the whole library by opening libtest.scad and that includes all the tests using relative paths and they all fail. It would be good if they worked so I can check everything else is working.

Also in an example project that has two scad files that also doesn't work because it uses the second file with a relative path.

**Comment by ochafik** [comment]
It *should* now work.

And with colors & customizer

https://ochafik.com/openscad2

<img width="557" alt="image" src="https://github.com/openscad/openscad-playground/assets/273860/97027a6d-2153-4d72-85d2-b06c32fafcf3">

**Comment by nophead** [comment]
Most tests now do work but why are the colours so milky? The example above should look like this: 

![image](https://github.com/openscad/openscad-playground/assets/566149/723b7df5-5484-4260-a207-9f5e3d1c2fbb)

Some tests don't complete but there is no log output to say why. The main.scad in that example fails in that way as well.

I think imported STL still have a problem with relative paths. There is a microview.scad test that imports STLs.

**Comment by ochafik** [comment]
thanks for giving it a spin!

Oh, importing STLs (and supporting attachments), high on my list!

Milky Colors are a bug in how I output the colors, feel free to file this (and the forever hang) separately to track.
