### ISSUE TITLE
Coordinate System Mismatch Between OpenSCAD and Model-Viewer

### ISSUE THREAD

**Issue by 01miaom** [openscad/openscad-playground#53]
Models created in OpenSCAD do not rotate correctly in Model-Viewer due to differing coordinate systems. Specifically, in Model-Viewer, the Y-axis seems to correspond to the Z-axis in OpenSCAD. This mismatch causes models to rotate diagonally instead of around the expected axes.

To correctly rotate models in Model-Viewer, a `rotate([-90, 0, 0])` adjustment is required in OpenSCAD.

Would it be possible to consider incorporating automatic rotation adjustments to account for this coordinate system mismatch directly into the code? This would help ensure consistent rotation behavior between OpenSCAD and Model-Viewer.

**Comment by ochafik** [comment]
@01miaom thanks for reporting this! I'd forgotten about that annoying quirk, now fixed!
