### ISSUE TITLE
🚨 Playground Broken

### ISSUE THREAD

**Issue by joeskeen** [openscad/openscad-playground#55]
Currently the playground does not render anything when you go to it:

![image](https://github.com/user-attachments/assets/69f5b430-a838-4f5b-8f2e-8f233f1cee83)

Clicking "Render" makes a success sound but still no preview.

This developer console error is perhaps related?

![image](https://github.com/user-attachments/assets/5cbefb53-154c-4677-9434-d4c2a46d200f)

```
Access to script at 'https://unpkg.com/@google/model-viewer@3.5.0/dist/model-viewer.min.js' (redirected from 'https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js') from origin 'https://ochafik.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Tested on Linux Mint 21.3 in Chrome, Edge, Firefox.

**Comment by joeskeen** [comment]
Looks like a Bad Gateway on unpkg.com... Not sure if this is a temporary or more permanent outage. If this becomes a more long-term or frequent issue, we should consider including the package in the deployment of the playground itself (so it is as available as the playground itself). I'd be happy to help with that if needed.

**Comment by t-paul** [comment]
Works fine here, so it's likely some sort of CDN issue.

![image](https://github.com/user-attachments/assets/13281643-938c-4260-8854-c1a218d2efb8)

**Comment by t-paul** [comment]
As for packaging/deploying, it would be an option to deploy on the OpenSCAD file server. This would mostly mean a docker image as that's the current setup on the server.
So far @ochafik has kindly hosted the playground. Having an additional "beta"? deployment on `playground.openscad.org` or so would be nice.

**Comment by joeskeen** [comment]
Looks like it isn't all of upkg.com - this link is working fine: <https://unpkg.com/react@16.7.0/umd/react.production.min.js>.

I tried switching to the browse URL and get this:

<https://unpkg.com/browse/@google/model-viewer@3.5.0>
> Not found: @google/model-viewer@3.5.0

**Comment by joeskeen** [comment]
This seems to be related: https://github.com/mjackson/unpkg/issues/398

**Comment by joeskeen** [comment]
Is there any reason the playground couldn't be hosted using GitHub Pages? Or is it already, just hooked up to the @ochafik domain?

**Comment by joeskeen** [comment]
Another interesting thing: I just searched the repo for `@google/model-viewer` and didn't see any code results. This means that this critical script is being loaded from a dependency dynamically at runtime instead of being an explicit dependency of the project. I will need to do some more digging later as I need to go to work right now, but I think that's a crucial part of solving this issue from happening in the future.

**Comment by joeskeen** [comment]
Looks like the `@google/model-viewer` reference only appears in the branch that is currently deployed: <https://github.com/ochafik/openscad-playground/tree/color-assimp2>

So it's not a dynamic dependency, it's just not merged to main. @ochafik, any reason this couldn't just be bundled in at build-time?

**Comment by ochafik** [comment]
Hi all, thanks for reporting & diagnosing the issue!

modelviewer “used to recommend unpkg, but it has had several serious outages recently” (from their [faq](https://modelviewer.dev/docs/faq.html)). I’ll try to bundle the does (or switch to the Google cdn) later today.

**Comment by ochafik** [comment]
I've deployed a fixed playground ([hitting Google CDN](https://github.com/ochafik/openscad-playground/commit/3cc0090e9fb24a7a2c82b6ed2458b8610785c83f)).

I'll look into bundling of the deps as a follow up, tracking in https://github.com/openscad/openscad-playground/issues/56

Thanks again!

**Comment by ochafik** [comment]
The playground should now work completely offline (after the first load).
