### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by joeskeen** [openscad/openscad-playground#7]
According to the [OpenSCAD User Manual/First Steps/Changing the color of an object](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/First_Steps/Changing_the_color_of_an_object) example:

```scad
color([1,0,0]) cube([2,3,4]);
translate([3,0,0])
color([0,1,0]) cube([2,3,4]);
translate([6,0,0])
color([0,0,1]) cube([2,3,4]);
```

should look like this:
![image](https://github.com/openscad/openscad-playground/assets/12286274/bc1bfebc-d2a4-4c82-a5dc-0ec4b4d31532)

but in the openscad playground looks like this:
![image](https://github.com/openscad/openscad-playground/assets/12286274/ea104854-3f82-47fd-b6ad-f1daf894bc1c)

Having different pieces rendered in different colors is very useful when designing practical parts that may fit around other pieces.

**Comment by t-paul** [comment]
OpenSCAD only supports colors in Preview mode and the WASM version does not support this mode at all. So for the time being we can only document that somewhere.

The OpenGL updates that are currently in progress might bring Preview support, full color mode is quite high on the wishlist but unlikely to happen any time soon unless someone jumps at that topic.

**Comment by enemali** [comment]
adding colors will be very useful , i want  to use this to teach kids

**Comment by Scopeuk** [comment]
As noted in https://github.com/openscad/openscad-playground/issues/34#issuecomment-2203209642 this is starting to be integrated. It is still under development.
