### ISSUE TITLE
Position of rendering is different from OpenSCAD

### ISSUE THREAD

**Issue by stockholmux** [openscad/openscad-playground#8]
If you run the script `playground.scad` in OpenSCAD proper, the model is centred on the x/y/z axes.

Example:
<img width="486" alt="Screen Shot 2023-08-06 at 2 18 52 PM" src="https://github.com/openscad/openscad-playground/assets/1152927/a8756fdc-34cc-4c1c-85ed-6d712818a0a1">

In the playground, it seems to be at the lower left of the bounding box.

Example:
![Screen Shot 2023-08-06 at 2 18 46 PM](https://github.com/openscad/openscad-playground/assets/1152927/68927ed5-ae9e-4aa6-b267-12f9d56342e9)

Someone learning OpenSCAD with the playground will be quite thrown off by this, especially of they are doing 0 centred modelling.

**Comment by UBaer21** [comment]
I can understand the confusion as WASM is using an stl viewer without any origin or grid markers. 
So you can mistaken the 3D-gizmo as origin. But you will see a similar thing also in the lower left corner of the OpenSCAD view window 
![image](https://github.com/openscad/openscad-playground/assets/93376232/fad3f299-2d57-4e12-9cd4-be0060961a29)

But the position of the objects is identical - and the exported files also contain the same positions.

**Comment by t-paul** [comment]
Yep, it seems the axis marker is positioned at the bounding box of the model. At first glance, I'm not seeing a property to enable some sort of grid.

**Comment by t-paul** [comment]
Hmm, there's https://github.com/gabotechs/react-stl-viewer/blob/master/src/StlViewer/SceneElements/Floor.tsx which sounds like there's support for some x/y plane thingy.

**Comment by stockholmux** [comment]
Humm. I noticed it when I experimented with `positionX` and `positionY` to 0 in `StlViewer` (file: `ViewerPanel.tsx`) and it corrected the axes.

<img width="514" alt="Screen Shot 2023-08-06 at 4 13 31 PM" src="https://github.com/openscad/openscad-playground/assets/1152927/aa11b5f4-28c2-412a-94c4-190f01f670cd">

Now, if we want the 3D gizmo @UBaer21 it should probably position it in a fixed position and have rulers. 

I'm wrestling with `gabotechs/react-stl-viewer` currently, there doesn't seem like there are many options, especially regarding the camera. Seems like `pmndrs/react-three-fiber` has more options but less turnkey.

**Comment by UBaer21** [comment]
As you can see it is the now the center of the bounding box but not the origin - I would assume this would be even more confusing. 
You could add a rules as an object but as we have no real preview that object would render and need to be removed for the export. 
[like this](https://ochafik.com/openscad2/#%7B%22params%22%3A%7B%22sourcePath%22%3A%22%2Fplayground.scad%22%2C%22source%22%3A%22if(%24preview)for(s%3D%5B%5B20%2C.1%2C.1%5D%2C%5B.1%2C.1%2C20%5D%2C%5B.1%2C20%2C.1%5D%5D)cube(s%2Ctrue)%3B%5Cnsphere(5)%3B%22%2C%22features%22%3A%5B%22manifold%22%2C%22fast-csg%22%2C%22lazy-union%22%5D%7D%2C%22view%22%3A%7B%22layout%22%3A%7B%22mode%22%3A%22multi%22%2C%22editor%22%3Atrue%2C%22viewer%22%3Atrue%2C%22customizer%22%3Afalse%7D%2C%22color%22%3A%22%23241f05%22%2C%22showAxes%22%3Atrue%2C%22showShadows%22%3Atrue%7D%7D)

but as we have no colors in the viewer (which could work if 3mf color export would be implemented in openSCAD)
And you see that the axis marking will also influence the camera and bounding box - so i think this is not a solution. 

in https://ochafik.com/openscad is just nothing - so i think that bounding box edge gizmo is an improvement  - but sure it is not ideal .

**Comment by ochafik** [comment]
Filed https://github.com/gabotechs/react-stl-viewer/issues/55 for origin-bound axes

Although TBH on the long run I feel like we'd need either OpenGL emscripten support OR... gltf export + some color viewer such as https://modelviewer.dev/

**Comment by ochafik** [comment]
Note that axes have currently disappeared in the deployed [Web Playground](https://github.com/ochafik/openscad2) as I'm in the process of overhauling it (see https://github.com/openscad/openscad-playground/pull/37 ). I'm thinking of how best to reintroduce them (maybe a separate modelviewer w/ arrows synced on the main viewer).

**Comment by ochafik** [comment]
Closing this in favour of https://github.com/openscad/openscad-playground/issues/72

(fyi, about to add axes but still no rulers in https://github.com/openscad/openscad-playground/pull/71 )
