### ISSUE TITLE
Could not initialize localization (application path is '/')

### ISSUE THREAD

**Issue by kutu** [openscad/openscad-playground#80]
After recent update I got an error using NopSCADlib
![image](https://github.com/user-attachments/assets/c711d0c4-f29b-4b6c-b8a1-72586985067d)

Console
![image](https://github.com/user-attachments/assets/9a934a96-0127-4eba-8881-9ea5ea91d7f2)

In Network panel I only got errors for font loading, everything else loads successfully
![image](https://github.com/user-attachments/assets/7d3685f9-0f3b-45ef-8a0c-4e94933c65ba)

**Comment by ochafik** [comment]
@kutu thanks for reporting this! The crash should now be fixed (cf pending PR on OpenSCAD; it was preventing any library import  😅).

The localization and font errors aren’t blocking, but I will address too at some point :-)

**Comment by ochafik** [comment]
Added light e2e tests that exercice BOSL2 & NopSCADlib + removed localization warning in https://github.com/openscad/openscad-playground/pull/85

Thanks again for the report!
