### ISSUE TITLE
Multiple plugins for typescript

### ISSUE THREAD

**Issue by Rotzbua** [openscad/openscad-playground#99]
Two plugins for typescript are defined as dependency:

* rollup-plugin-typescript2
* @rollup/plugin-typescript

Only the first is used, but the second seems to be the official plugin.

Is there a reason for rollup-plugin-typescript2?

**Comment by ochafik** [comment]
Turns out there was no reason to stick to rollup, given we already have webpack for the main binary --> https://github.com/openscad/openscad-playground/pull/102
